---
- name: Deploy to Kubernetes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ensure kubectl is installed
      command: which kubectl
      register: kubectl_installed
      ignore_errors: yes

    - name: Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: kubectl_installed.rc != 0

    - name: Apply Deployment
      command: kubectl apply -f /var/lib/jenkins/workspace/portfolio-ramesh/deploy/deployment.yaml --validate=false
      register: deployment_result
      ignore_errors: yes

    - name: Show Deployment result
      debug:
        var: deployment_result

    - name: Apply Service
      command: kubectl apply -f /var/lib/jenkins/workspace/portfolio-ramesh/deploy/service.yaml --validate=false
      register: service_result
      ignore_errors: yes

    - name: Show Service result
      debug:
        var: service_result

    - name: Run a bash script
      command: /var/lib/jenkins/workspace/portfolio-ramesh/deploy/portforward.sh
      register: script_result
      ignore_errors: yes

    - name: Show script result
      debug:
        var: script_result